#!/bin/sh

# shellcheck disable=SC2015
# This imp has support for multiple files, heredocs, stdin, and ofc single files
# This imp is actually not an extremely basic version..
# infact theres no need for arg() or usage() to exist at all
# they are simply implemented for future use if option support is to be added

# minimum length WITH formating is 18 lines

print() {
  out="$(while read -r p; do
    IFS=""; echo "$p"
  done <&0)"
  IFS=""; echo "$out"
}
usage() {
  ${0} << EOF
(sh)cat: Pure SH cat replacement...
Usage:
  $0 [file|stdin]
Supports:
  - concatenating files ( $0 <file> <file2> <file3> )
  - stdin ( < file )
  - heredocs ( << EOF )
  - basic files ( $0 <file> )
EOF
}
acase() {
  case "$#" in
    0)
      print;;
    *)
      for i in "$@"; do
        print < "$i"
      done
    ;;
  esac
}
arg(){
while [ "$1" ]; do
  case "$1" in
    --help|-h)
      usage; exit 0;;
    *)
      acase "$@";;
  esac
  shift 1
done
}
[ "$1" ] && { arg "$@"; } || { acase "$@"; }
